### ISSUE TITLE
Create a frontend project

### ISSUE THREAD

**Issue by KPeen** [Energinet-DataHub/MightyDucks#61] opened 2021-06-30 11:15 UTC
- Create project in GitHub
- We have a folder structure that allows the frontend application to scale
- We have a folder structure that gives the best possible overview of how the cake is cut
- We made it easy to maintain the project
- Font Awesome is included as the icon library

**Comment by Renetnielsen** [comment] 2021-07-02 15:11
Can be closed, duplicate of https://github.com/Energinet-DataHub/dh3-admin/issues/4

**Closed by Renetnielsen** 2021-07-02 15:11 UTC
Labels: Mighty Ducks
